# CI de Nível 04 - Disparo manual a partir de 1 clique

# O que vai aparecer lá nas opções de piep
name: 'Execução Integrada'

# triggers OU gatilhos de execução // Regras de disparo da execução
# gatilho de exec manual = workflow_dispatch (GitHub Actions)

on:
  workflow_dispatch:

jobs:
  inspection:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn
      
      - name: Padronizacao de codigo (Lint/Prettier)
        run: yarn lint
      
  unit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Testes de Unidade
        run: yarn run test

      #descricao do job
  e2e-tests:
    # maquina que o job vai executar
    runs-on: ubuntu-latest

    # passo a passo das acoes do job
    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Instalando Playwright
        run: yarn playwright install

      - name: Testes E2E (end-to-end)
        run: yarn run e2e

      # passed, failed, cancelled
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./playwright-report
